version: "3"
services:
  frontend:
    image: frontend
    build: ./frederikflintcom

  backend:
    image: backend
    build: ./RedditShowerthoughts/RedditShowerthoughts


  proxy:
    image: proxy
    build: ./proxy
    ports:
        - "80:80"
    depends_on:
      - frontend
      
volumes:
  dbdata:
